# Generated by Django 5.1.2 on 2025-01-13 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='', max_length=10)),
                ('email', models.EmailField(default='', max_length=35, unique=True)),
                ('password', models.CharField(default='', max_length=10)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Other', max_length=10)),
                ('mob_num', models.CharField(default='', max_length=10)),
                ('city', models.CharField(default='', max_length=10)),
                ('reg_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
