# Generated by Django 5.1.2 on 2025-01-13 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_nm', models.CharField(max_length=10)),
                ('c_image', models.ImageField(upload_to='category/')),
            ],
        ),
    ]
