# Generated by Django 5.1.2 on 2025-01-16 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_registration_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='city',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
