# Generated by Django 5.1.2 on 2025-01-16 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_registration_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='cake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=450)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cake/')),
                ('price', models.FloatField(max_length=10)),
            ],
        ),
    ]
