# Generated by Django 5.1.2 on 2025-01-16 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_cake'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cake',
            name='description',
        ),
    ]
