# Generated by Django 5.1.3 on 2025-01-29 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_cake_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='p_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='qty',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_amt',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(default='Amreli'),
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(default='Amreli', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='mobile_no',
            field=models.CharField(default=7548965894, max_length=15),
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(default='Riva', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='pincode',
            field=models.CharField(default=362020, max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='registration',
            name='gender',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='registration',
            name='mob_num',
            field=models.CharField(max_length=10),
        ),
    ]
