# Generated by Django 5.1.3 on 2025-02-01 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_brownie_chocolate_chocolate_bouquet_donut_muffin_and_more'),
    ]

    operations = [
       
      
        
        
      
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='no',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='pin',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='order',
            name='qty',
            field=models.PositiveIntegerField(default=''),
        ),
    ]
