# Generated by Django 5.1.3 on 2025-01-31 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_cake_price_alter_order_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='qty',
            field=models.PositiveIntegerField(),
        ),
    ]
