# Generated by Django 5.1.3 on 2025-02-01 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_remove_order_date_remove_order_p_id_and_more'),
        ('myapp', '0012_alter_order_qty'),
    ]

    operations = [
    ]
