# Generated by Django 5.1.3 on 2025-02-08 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_merge_20250201_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pnm',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Product Name'),
        ),
        migrations.AddField(
            model_name='order',
            name='prp',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Product Price'),
        ),
        migrations.AddField(
            model_name='order',
            name='tp',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total Price'),
        ),
        migrations.AlterField(
            model_name='cake',
            name='price',
            field=models.FloatField(max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='qty',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='registration',
            name='password',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
