# Generated by Django 5.1.6 on 2025-02-08 10:40

from django.db import migrations, models # type: ignore


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_order_pnm_order_prp_order_tp_alter_cake_price_and_more'),
    ]

    operations = [
       
      
      
    ]
