# Generated by Django 5.1.3 on 2025-02-11 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_faq_remove_cake_description_remove_order_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FAQ',
        ),
        migrations.AlterField(
            model_name='category',
            name='c_nm',
            field=models.CharField(max_length=100),
        ),
    ]
