# Generated by Django 5.1.3 on 2025-02-12 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_delete_faq_alter_category_c_nm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='qty',
            new_name='pprice',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='pid',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='price',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='total',
        ),
      
        migrations.AddField(
            model_name='cart',
            name='pname',
            field=models.CharField(default='null', max_length=10),
        ),
    ]
