# Generated by Django 5.1.3 on 2025-02-13 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_rename_qty_cart_pprice_remove_cart_pid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='pname',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='cart',
            name='pprice',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
