# Generated by Django 5.1.3 on 2025-02-13 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_alter_cart_pname_alter_cart_pprice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='p_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='p_nm',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='c_nm',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='qty',
        ),
    ]
