# Generated by Django 5.1.3 on 2025-02-14 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_alter_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='new_arrivals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aname', models.CharField(max_length=50)),
                ('aprice', models.IntegerField()),
            ],
        ),
    ]
