# Generated by Django 5.1.3 on 2025-02-14 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_new_arrivals'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewArrivals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aname', models.CharField(max_length=50)),
                ('aprice', models.IntegerField()),
                ('aimage', models.ImageField(blank=True, null=True, upload_to='new_arrivals/')),
            ],
        ),
        migrations.DeleteModel(
            name='new_arrivals',
        ),
    ]
