# Generated by Django 5.1.3 on 2025-02-14 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_newarrivals_delete_new_arrivals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='no',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pin',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pnm',
        ),
        migrations.RemoveField(
            model_name='order',
            name='prp',
        ),
        migrations.RemoveField(
            model_name='order',
            name='qty',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tp',
        ),
        migrations.AddField(
            model_name='order',
            name='mobile_number',
            field=models.CharField(default='0000000000', max_length=15),
        ),
        migrations.AddField(
            model_name='order',
            name='pincode',
            field=models.CharField(default='000000', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='product_name',
            field=models.CharField(default='Unknown Product', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='product_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(default='No address provided'),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(default='Unknown City', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(default='Guest', max_length=100),
        ),
    ]
