# Generated by Django 5.1.3 on 2025-02-14 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_remove_order_no_remove_order_pin_remove_order_pnm_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='mobile_number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product_price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
        migrations.AddField(
            model_name='order',
            name='no',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='pin',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AddField(
            model_name='order',
            name='pnm',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Product Name'),
        ),
        migrations.AddField(
            model_name='order',
            name='prp',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Product Price'),
        ),
        migrations.AddField(
            model_name='order',
            name='qty',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='order',
            name='tp',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total Price'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
