# Generated by Django 5.1.3 on 2025-02-15 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_remove_order_mobile_number_remove_order_pincode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.CharField(blank=True, default='Unknown', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='city',
            field=models.CharField(blank=True, default='Unknown', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='email',
            field=models.EmailField(blank=True, default='guest@example.com', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Other', max_length=10),
        ),
        migrations.AlterField(
            model_name='registration',
            name='mob_num',
            field=models.CharField(blank=True, default='0000000000', max_length=10),
        ),
        migrations.AlterField(
            model_name='registration',
            name='password',
            field=models.CharField(blank=True, default='defaultpassword', max_length=128),
        ),
        migrations.AlterField(
            model_name='registration',
            name='user_name',
            field=models.CharField(blank=True, default='Guest', max_length=50),
        ),
    ]
