# Generated by Django 5.1.3 on 2025-02-15 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_order_user_alter_registration_city_and_more'),
    ]

    operations = [
      
    ]
