# Generated by Django 5.1.3 on 2025-02-15 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_alter_order_user'),
    ]

    operations = [
        
    ]
