# Generated by Django 5.1.3 on 2025-02-17 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_alter_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
