# Generated by Django 5.1.3 on 2025-02-17 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_remove_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='pnm',
        ),
        migrations.RemoveField(
            model_name='order',
            name='prp',
        ),
        migrations.RemoveField(
            model_name='order',
            name='qty',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tp',
        ),
        migrations.AddField(
            model_name='order',
            name='cart_items',
            field=models.JSONField(default='None'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='no',
            field=models.CharField(default='', max_length=15, verbose_name='Mobile Number'),
        ),
    ]
