# Generated by Django 5.1.3 on 2025-02-17 06:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_remove_order_pnm_remove_order_prp_remove_order_qty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ordered_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='order',
            name='cart_items',
            field=models.JSONField(default=list),
        ),
    ]
