# Generated by Django 5.1.6 on 2025-02-18 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0037_registration_user_name_alter_registration_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='user',
        ),
    ]
