# Generated by Django 5.1.3 on 2025-02-20 05:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0044_order_user_alter_profile_profile_picture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart_items',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ordered_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AddField(
            model_name='order',
            name='pnm',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Product Name'),
        ),
        migrations.AddField(
            model_name='order',
            name='prp',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Product Price'),
        ),
        migrations.AddField(
            model_name='order',
            name='qty',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='order',
            name='tp',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total Price'),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='no',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.CreateModel(
            name='OrderCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('no', models.CharField(default='', max_length=15, verbose_name='Mobile Number')),
                ('pin', models.CharField(default='', max_length=6)),
                ('city', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('address', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('payment_method', models.CharField(blank=True, default='', max_length=50)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cart_items', models.JSONField(default=list)),
                ('ordered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
