# Generated by Django 5.1.3 on 2025-02-20 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0045_remove_order_cart_items_remove_order_ordered_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordercart',
            name='cart_items',
        ),
        migrations.RemoveField(
            model_name='ordercart',
            name='name',
        ),
        migrations.RemoveField(
            model_name='ordercart',
            name='no',
        ),
        migrations.RemoveField(
            model_name='ordercart',
            name='ordered_at',
        ),
        migrations.RemoveField(
            model_name='ordercart',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='ordercart',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='ordercart',
            name='user',
        ),
        migrations.AddField(
            model_name='ordercart',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=1),
        ),
        migrations.AddField(
            model_name='ordercart',
            name='customer_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordercart',
            name='item_image',
            field=models.URLField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordercart',
            name='item_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordercart',
            name='item_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordercart',
            name='mobile',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordercart',
            name='paymentMethod',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordercart',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordercart',
            name='totalAmount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordercart',
            name='address',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordercart',
            name='city',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordercart',
            name='pin',
            field=models.CharField(max_length=10),
        ),
    ]
