# Generated by Django 5.1.3 on 2025-02-20 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0046_remove_ordercart_cart_items_remove_ordercart_name_and_more'),
    ]

   
