# Generated by Django 5.1.3 on 2025-02-20 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0047_remove_ordercart_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordercart',
            name='created_at',
        ),
    ]
