# Generated by Django 5.1.3 on 2025-02-20 05:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0048_remove_ordercart_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercart',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
