# Generated by Django 5.1.3 on 2025-02-20 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0049_ordercart_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercart',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
