# Generated by Django 5.1.3 on 2025-02-20 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0051_remove_ordercart_item_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordercart',
            name='item_image',
        ),
        migrations.RemoveField(
            model_name='ordercart',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='ordercart',
            name='item_price',
        ),
        migrations.RemoveField(
            model_name='ordercart',
            name='quantity',
        ),
    ]
