# Generated by Django 5.1.3 on 2025-02-21 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0053_order_created_at_order_order_status_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordercartitem',
            name='order',
        ),
        migrations.DeleteModel(
            name='OrderCart',
        ),
        migrations.DeleteModel(
            name='OrderCartItem',
        ),
    ]
